apiVersion: batch/v1
kind: Job
metadata:
  name: sreg-storage-load
  namespace: ns-admin
spec:
  ttlSecondsAfterFinished: 604800
  backoffLimit: 1
  template:
    spec:
      hostAliases:
        - ip: 192.168.10.70
          hostnames:
            - sealos.hub
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Never
      containers:
        - name: sreg-storage
          image: ghcr.io/labring/sreg-storage:sha-68572e8
          imagePullPolicy: IfNotPresent
          command: ["/usr/local/bin/sreg-storage.sh", "load", "--config=/config/config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tmp
              mountPath: /tmp/sreg-storage
            - name: image-cri-shim-config
              mountPath: /etc/image-cri-shim.yaml
              readOnly: true
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
      volumes:
        - name: config
          configMap:
            name: sreg-storage-load-config
        - name: tmp
          emptyDir:
            sizeLimit: 20Gi
        - name: image-cri-shim-config
          hostPath:
            path: /etc/image-cri-shim.yaml
            type: File
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sreg-storage-load-config
  namespace: ns-admin
data:
  config.yaml: |
    rclone:
      remote: "myremote"
      config:
        type: "s3"
        provider: "Other"
        endpoint: "objectstorageapi.192.168.10.70.nip.io"
        access_key_id: "admin"
        secret_access_key: "lvn25znf4tl5mtww"
        no_check_certificate: true
        s3-no-check-bucket: true
    tmp_dir: "/tmp/sreg-storage"
    load:
      source:
        remote: "myremote:admin-test-sreg/registry-backups/registry-20260313093103.tar.gz"
      extract_dir: "/tmp/sreg-storage/extracted"
      local_registry:
        port: 15001
      dest_registry:
        url: "sealos.hub:5000"
